// Generated by CoffeeScript 1.9.3
var SMON, smon;

smon = require('../src/stormmonitor');

SMON = new smon(10000);

SMON.on('results', function(result) {
  console.log("Event results received");
  return console.log(result);
});

SMON.addpid(3629);

SMON.run();
